version: '3.7'

services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - '2358:2358'
    privileged: true
    restart: always
    depends_on:
      - db
      - redis
    env_file: judge0.conf

  workers:
    image: judge0/judge0:1.13.1
    command: ['./scripts/workers']
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    depends_on:
      - db
      - redis
    env_file: judge0.conf

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - judge0-db:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2.4
    command:
      ['redis-server', '--appendonly', 'yes', '--requirepass', '${REDIS_PASSWORD:-judge0redis}']
    env_file: judge0.conf
    volumes:
      - judge0-redis:/data
    restart: always

volumes:
  judge0-db:
  judge0-redis:
